# Kontaktdetails
contact:
  fullName: "4E Schwertberg - erneuerbare Energie effizient einsetzen"
  mailInfo: "info@4e-schwertberg.at"
  mailRegister: "anmeldung@4e-schwertberg.at"
  phoneNumber: "+43 677 629 39 156"
  street: "Unterkogelbergstraße 1"
  zip: "4311"
  town: "Schwertberg"
  boardMember: [
    {
      "role": "Obmann",
      "firstName": "Florian",
      "lastName": "Nairz"
    },
    {
      "role": "Obmann-Stv.",
      "firstName": "Oskar",
      "lastName": "Almeder"
    },
    {
      "role": "Kassierin",
      "firstName": "Beatrix",
      "lastName": "Hinterkörner"
    },{
      "role": "Kassier-Stv.",
      "firstName": "Johannes",
      "lastName": "Tinschert"
    },
    {
      "role": "Schriftführerin",
      "firstName": "Sarah",
      "lastName": "Loch"
    },
    {
      "role": "Schriftführer-Stv.",
      "firstName": "Rainer",
      "lastName": "Gradl"
    },
    {
      "role": "Vorstandsmitglied lt. Statuten §11 Abs. 1 (Umweltausschussvorsitzender der Gemeinde Schwertberg)",
      "firstName": "Andreas",
      "lastName": "Karlinger"
    }
  ]

details:
  zvr: "1922887273"
  uid: "ATU80460519"

# Kosten und Preise
costs:
  membershipFeeWithVAT: "15"
  vat: "20%"
  price_buyer: "12"
  price_buyer_unit: "ct/kWh"
  price_seller: "10"
  price_seller_unit: "ct/kWh"
  price_last_change: "01.04.2026"

  energy_chart:
    conventional:
      grid: 6.057
      levies: 0.723
      taxPercent: 20.0
    eeg:
      regional:
        grid: 4.497
        levies: 0.0
        taxPercent: 20.0

# Formulare und verlinkte Dokumente
form_buyer:
  url: "/assets/docs/Aufnahmeantrag-Kaeufer.pdf"
  text: "Anmeldeformular Bezieher"
form_buyer_seller_url:
  url: "/assets/docs/Aufnahmeantrag-Einspeiser.pdf"
  text: "Anmeldeformular Einspeiser"
statuten:
  url: "/assets/docs/Vereinsstatuten_4E_Schwertberg.pdf"
